core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
	# path('', TemplateView.as_view(template_name='home.html'), name='home'),
	path('', include('portal.urls')),
	path('subscriber/', include('subscriber.urls')),
    path('admin/', admin.site.urls),
]

portal/urls.py
from django.urls import path, include

from portal.views import HomePageView, PricingPageView, AboutPageView, ContactPageView

app_name = 'portal'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('pricing/', PricingPageView.as_view(), name='pricing'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('contact/', ContactPageView.as_view(), name='contact'),
]

subscriber/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from subscriber.views import supplier_logout, SupplierLoginFormView, RegistrationFormView, ContinueRegistrationFormView, ResetPasswordFormView, UserOppurtunityPreferenceView, VerifyOtpFormView, ResendOtpView

# get_started, get_coupon, reset_password, registration_success, registration_active

app_name = 'subscriber'

urlpatterns = [
    path('login/', SupplierLoginFormView.as_view(), name='login'),
    path('verify-otp/', VerifyOtpFormView.as_view(), name='verify_otp'),
    path('resend-otp/', ResendOtpView.as_view(), name='resend_otp'),
    path('test/', TemplateView.as_view(template_name='subscriber/notifications/thank-you.html')),
    path('logout/', supplier_logout, name='logout'),
    path('forget-password/', ResetPasswordFormView.as_view(), name='forget_password'),
    # path('reset-password/<code>/', reset_password, name='reset_password'),
    
    path('registration/', RegistrationFormView.as_view(), name='registration'),

    # path('registration/<activation_code>/active/', registration_active, name='registration-active'),
    path('registration/continue/<activation_code>/', ContinueRegistrationFormView.as_view(), name='registration_landing_activate'),

    # path('<uid>/registration/success/', registration_success, name='registration-success'),

    # path('get-started/', get_started, name='get-started'),

    # path('get-coupon/<code>/', get_coupon, name='get-coupon'),

    # # url(r'^payment/$', 'supplier.views.payment', name='payment'),
    # path('payment/create/$', 'subscriber.views.payment_create', name='payment_create'),
    # path('payment/execute/$', 'subscriber.views.payment_execute', name='payment_execute'),
    # path('payment/success/$', 'subscriber.views.payment_success', name='payment_success'),
    # path('payment/error/$', 'subscriber.views.payment_error', name='payment_error'),
    # path('save/user-prefernce/$', UserOppurtunityPreferenceView.as_view(), name='user_oppr_pref'),
]

portal/models.py
from django.db import models

# Create your models here.

portal/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    """
    Home page view
    """
    template_name = 'portal/homepage.html'
    

class PricingPageView(TemplateView):
    """
    Princing Page view
    """
    template_name = 'portal/pricing.html'
    
    
class AboutPageView(TemplateView):
    """
    About page view
    """
    template_name = 'portal/about.html'
    
    
class ContactPageView(TemplateView):
    """
    Contact page view
    """
    template_name = 'portal/contact.html'

portal/templates/portal/base/body.html
{% extends 'portal/base/head.html' %}
{% load static %}

{% block body_content %}

    {% block body %}

        <!-- BEGIN HEADER -->
        <div id="top-wrapper">
            {% block top_wrapper %}

            {% endblock %}
        </div>
        <!-- END HEADER -->


        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN CONTENT -->
            {% block page_container %}
            {% endblock page_container %}
            <!-- END PAGE CONTENT BODY -->
            <!-- END CONTENT BODY -->
        </div>
        <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->


        <!-- BEGIN FOOTER -->
        <!-- BEGIN PRE-FOOTER -->
        <div class="page-prefooter">
            {% block page_prefooter %}
            {% endblock page_prefooter %}
        </div>
        <!-- END PRE-FOOTER -->

        <!-- BEGIN INNER FOOTER -->
        <div class="page-footer">
            {% block page_footer %}
            {% endblock page_footer %}
        </div>
        <div class="scroll-to-top">
            <i class="icon-arrow-up"></i>
        </div>
        <!-- END INNER FOOTER -->
        <!-- END FOOTER -->
    {% endblock body %}

    {% block layout_scripts %}
        <!--[if lt IE 9]>
        <script src="{% static 'portal/assets/global/plugins/respond.min.js' %}"></script>
        <script src="{% static 'portal/assets/global/plugins/excanvas.min.js' %}"></script>
        <![endif]-->

        <!-- BEGIN CORE PLUGINS -->
        <script src="{% static 'portal/assets/global/plugins/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'portal/assets/global/plugins/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'portal/assets/global/plugins/js.cookie.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'portal/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'portal/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'portal/assets/global/plugins/jquery.blockui.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'portal/assets/global/plugins/uniform/jquery.uniform.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'portal/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js' %}" type="text/javascript"></script>
        <!-- END THEME LAYOUT SCRIPTS -->
    {% endblock layout_scripts %}

    {% block extra_layout_scripts %}
        <!-- END CORE PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="{% static 'portal/assets/global/scripts/app.min.js' %}" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <script src="{% static 'portal/assets/layouts/layout3/scripts/layout.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'portal/assets/layouts/layout3/scripts/demo.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'portal/assets/layouts/layout3/scripts/quick-sidebar.min.js' %}" type="text/javascript"></script>

        <script src="{% static 'portal/assets/global/plugins/jquery-validation/js/jquery.validate.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'portal/assets/global/plugins/jquery-validation/js/additional-methods.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'portal/assets/global/plugins/select2/js/select2.full.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'subscriber/assets/pages/scripts/login.min.js' %}" type="text/javascript"></script>

    {% endblock extra_layout_scripts %}




{% endblock body_content %}

portal/templates/portal/base/footer.html
{% load static %}
    <div class="container text-center">
        <img src="{% static 'portal/assets/images/logo-white.png' %}" alt="logo" class="logo-footer">
        <div>Copyright &copy; 2013 - 2015. eSupplierPortal.  All rights reserved. Designed in Arizona. Made all over the world</div>
    </div>

portal/templates/portal/base/head.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
		<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <title>{% block title %}eSupplier | Home {% endblock title %}</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.2.3/css/simple-line-icons.css">
        <link href="{% static 'portal/assets/global/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'portal/assets/global/plugins/simple-line-icons/simple-line-icons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'portal/assets/global/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'portal/assets/global/plugins/uniform/css/uniform.default.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'portal/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="{% static 'portal/assets/global/css/components-md.min.css' %}" rel="stylesheet" id="style_components" type="text/css" />
        <link href="{% static 'portal/assets/global/css/plugins-md.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN PAGE LEVEL STYLES -->

        <link href="{% static 'portal/assets/pages/css/about.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <link href="{% static 'portal/assets/layouts/layout3/css/layout.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'portal/assets/layouts/layout3/css/themes/default.min.css' %}" rel="stylesheet" type="text/css" id="style_color" />
        <link href="{% static 'portal/assets/global/css/components-rounded.css' %}" rel="stylesheet" id="style_components" type="text/css" />

        <link href="{% static 'portal/assets/layouts/layout3/css/custom.min.css' %}" rel="stylesheet" type="text/css" />

        {% block extra_css %}
        {% endblock extra_css %}

        <link rel="shortcut icon" href="{% static 'portal/assets/images/favicon.ico' %}" />
	</head>
    <!-- END HEAD -->

     <body class="{% block body_classes %}page-container-bg-solid page-boxed page-md homepage{% endblock body_classes %}">

     {% block body_content %}

     {% endblock body_content %}


    </body>

</html>

portal/templates/portal/base/page.html
{% extends 'portal/base/body.html' %}
{% load static %}

{% block extra_css %}
    <link href="{% static 'portal/assets/layouts/layout3/css/layout.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'portal/assets/layouts/layout3/css/themes/default.min.css' %}" rel="stylesheet"
          type="text/css" id="style_color"/>
    <link href="{% static 'portal/assets/layouts/layout3/css/custom.min.css' %}" rel="stylesheet" type="text/css"/>
{% endblock extra_css %}

{% block top_wrapper %}

    <div class="page-header">
        <!-- BEGIN HEADER TOP -->
        <div class="page-header-top">
            <div class="container">
                <!-- BEGIN LOGO -->
                <div class="page-logo">
                    <a href="{% url 'portal:home' %}">
                        <img src="{% static 'portal/assets/images/logo.png' %}" alt="logo" class="logo-default">
                    </a>
                </div>
                <!-- END LOGO -->
                <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- END RESPONSIVE MENU TOGGLER -->
                <!-- BEGIN TOP NAVIGATION MENU -->

                <div class="hor-menu">
                    <ul id="Navbar" class="nav navbar-nav pull-right collapse navbar-collapse">
                        <li class="active">
                            <a href="{% url 'portal:home' %}">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'portal:pricing' %}">Pricing</a>
                        </li>
                        <li>
                            <a href="{% url 'portal:contact' %}">Contact</a>
                        </li>
                        <li class="login-top">
                            {% if request.user.is_authenticated %}
                                <a class="btn btn-lg" href="{% url 'supplier:dashboard' %}">Dashboard</a>
                            {% else %}
                                <a class="btn btn-lg" href="{% url 'subscriber:login' %}">Login</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
                <!-- END TOP NAVIGATION MENU -->
            </div>
        </div>
        <!-- END HEADER TOP -->
    </div>
    <div class="showcase text-center">
        <div class="container">
            <div class="row margin-bottom-40">
                <div class="col-md-12">
                    <h2 class="text-right"><b>You're Just One Click Away From</b></h2>

                    <h2 class="text-right"><b>Registering Your Business on</b></h2>

                    <h2 class="margin-bottom-40 text-right"><b>Hundreds of Corporation Portals!</b></h2>

                    <h3>Create your <b>FREE</b> supplier account now:</h3>

                    <form class="form-inline register-form" role="form" id="register-now"
                          action="{% url 'subscriber:registration' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" name="first_name" placeholder="Name"
                                   autcomplete="off">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" name="email" placeholder="Email"
                                   autocomplete="off">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-lg orange">Free Account</button>
                            <p>
                                <small>By clicking 'Free Account' you agree to the ESupplier Portal <a
                                        href="javascript:;">Terms of Use</a> and <a href="javascript:;">Privacy
                                    Policy</a>.
                                </small>
                            </p>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock top_wrapper %}

{% block page_prefooter %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-12 col-xs-12 footer-block">
                <h2>COMPANY</h2>
                <ul class="nav nav-pills footer-menu">
                    <li role="presentation"><a href="#">About</a></li>
                    <li role="presentation"><a href="#">Support</a></li>
                    <li role="presentation"><a href="#">Blog</a></li>
                    <li role="presentation"><a href="#">Privacy Policy</a></li>
                    <li role="presentation"><a href="#">Terms of Service</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6 col-xs12 footer-block">
                <h2>SOCIAL</h2>
                <ul class="social-icons">
                    <li>
                        <a href="javascript:;" data-original-title="facebook" class="facebook"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="twitter" class="twitter"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="linkedin" class="linkedin"></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                <h2>CONTACT</h2>

                <p><a href="#">enquiries@esupplierportal.com</a></p>
            </div>
        </div>
    </div>
{% endblock page_prefooter %}


{% block page_footer %}
    <div class="container text-center">
        <img src="{% static 'portal/assets/images/logo-white.png' %}" alt="logo" class="logo-footer">

        <div>Copyright &copy; 2013 - 2015. eSupplierPortal. All rights reserved. Designed in Arizona. Made all over the
            world
        </div>
    </div>
{% endblock page_footer %}

portal/templates/portal/base/pre_footer.html
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-12 col-xs-12 footer-block">
                <h2>COMPANY</h2>
                <ul class="nav nav-pills footer-menu">
                    <li role="presentation"><a href="{% url 'portal:about' %}">About</a></li>
                    <li role="presentation"><a href="#">Support</a></li>
                    <li role="presentation"><a href="#">Blog</a></li>
                    <li role="presentation"><a href="#">Privacy Policy</a></li>
                    <li role="presentation"><a href="#">Terms of Service</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6 col-xs12 footer-block">
                <h2>SOCIAL</h2>
                <ul class="social-icons">
                    <li>
                        <a href="javascript:;" data-original-title="facebook" class="facebook"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="twitter" class="twitter"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="linkedin" class="linkedin"></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                <h2>CONTACT</h2>
                <p><a href="#">enquiries@esupplierportal.com</a></p>
            </div>
        </div>
    </div>