core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
	# path('', TemplateView.as_view(template_name='home.html'), name='home'),
	path('', include('portal.urls')),
	path('subscriber/', include('subscriber.urls')),
    path('admin/', admin.site.urls),
]

portal/urls.py
from django.urls import path, include

from portal.views import HomePageView, PricingPageView, AboutPageView, ContactPageView

app_name = 'portal'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('pricing/', PricingPageView.as_view(), name='pricing'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('contact/', ContactPageView.as_view(), name='contact'),
]

subscriber/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from subscriber.views import supplier_logout, SupplierLoginFormView, RegistrationFormView, ContinueRegistrationFormView, ResetPasswordFormView, UserOppurtunityPreferenceView, VerifyOtpFormView, ResendOtpView

# get_started, get_coupon, reset_password, registration_success, registration_active

app_name = 'subscriber'

urlpatterns = [
    path('login/', SupplierLoginFormView.as_view(), name='login'),
    path('verify-otp/', VerifyOtpFormView.as_view(), name='verify_otp'),
    path('resend-otp/', ResendOtpView.as_view(), name='resend_otp'),
    path('test/', TemplateView.as_view(template_name='subscriber/notifications/thank-you.html')),
    path('logout/', supplier_logout, name='logout'),
    path('forget-password/', ResetPasswordFormView.as_view(), name='forget_password'),
    # path('reset-password/<code>/', reset_password, name='reset_password'),
    
    path('registration/', RegistrationFormView.as_view(), name='registration'),

    # path('registration/<activation_code>/active/', registration_active, name='registration-active'),
    path('registration/continue/<activation_code>/', ContinueRegistrationFormView.as_view(), name='registration_landing_activate'),

    # path('<uid>/registration/success/', registration_success, name='registration-success'),

    # path('get-started/', get_started, name='get-started'),

    # path('get-coupon/<code>/', get_coupon, name='get-coupon'),

    # # url(r'^payment/$', 'supplier.views.payment', name='payment'),
    # path('payment/create/$', 'subscriber.views.payment_create', name='payment_create'),
    # path('payment/execute/$', 'subscriber.views.payment_execute', name='payment_execute'),
    # path('payment/success/$', 'subscriber.views.payment_success', name='payment_success'),
    # path('payment/error/$', 'subscriber.views.payment_error', name='payment_error'),
    # path('save/user-prefernce/$', UserOppurtunityPreferenceView.as_view(), name='user_oppr_pref'),
]

subscriber/models.py
from django.db import models

# Create your models here.

subscriber/views.py
from django.shortcuts import render
from django.views.generic import FormView
from django.views.generic.base import View
from django.views.generic import TemplateView
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import csrf_protect
from subscriber.forms import VerifyOtpForm, AuthenticationForm, CreateUserAccount, PasswordResetForm, RegistrationForm
# Create your views here.

def supplier_logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('subscriber:login'))
    
class ResetPasswordFormView(FormView):
    """
    Reset password form view...
    """
    form_class = PasswordResetForm
    template_name = 'subscriber/forget_password.html'

    def form_valid(self, form):
        """
        Form valid...
        """
        email = form.cleaned_data.get('email')
        user = User.objects.get(email=email)

        activation_code = md5(str(uuid.uuid4())).hexdigest()

        code = ActivationCode.objects.create(
            code=activation_code,
            user=user,
            creation_date=datetime.now(),
            code_for=1,
            status=0
        )
        email_message = NewEmail(template='password_reset',
                                 context={'user': user,
                                          'reset_code': code.code,
                                          'request': self.request
                                          },
                         subject='Account password reset', to=email
                         )
        email_message.send()

        return render(self.request,
                      'subscriber/notifications/forget_password.html',
                      {'email_sent': True, 'email': email}
                      )


class ContinueRegistrationFormView(FormView):
    """
    Finish the registration flow, the flow started from LandingPage Registration
    """
    form_class = CreateUserAccount
    template_name = 'subscriber/continue_registration.html'

    def __init__(self, *args, **kwargs):
        self.activation_code = None
        return super(ContinueRegistrationFormView, self).__init__(*args, **kwargs)

    def dispatch(self, *args, **kwargs):
        if self.request.method == 'GET':

            self.activation_code = RegisterNowActivationCode.objects.get(
                code=self.kwargs.get('activation_code')
            )
            if self.activation_code.is_expired:
                return HttpResponseRedirect(reverse('registration'))

        return super(ContinueRegistrationFormView, self).dispatch(*args, **kwargs)

    def get_initial(self):
        self.activation_code = RegisterNowActivationCode.objects.get(
                code=self.kwargs.get('activation_code')
            )
        return dict(
            first_name=self.activation_code.first_name,
            email=self.activation_code.email
        )

    def get_context_data(self, **kwargs):
        context = super(ContinueRegistrationFormView, self).get_context_data(**kwargs)
        context['activation_code'] = self.activation_code.code

        return context

    def form_valid(self, form):
        form.cleaned_data['first_name'] = self.activation_code.first_name
        form.cleaned_data['email'] = self.activation_code.email
        user_created = form.save()
        user_created.is_active = True
        user_created.save()

        #New user profile creation
        usr_profile, created = UserProfile.objects.get_or_create(user=user_created)
        usr_profile.profile_image = form.cleaned_data['profile_image']
        usr_profile.phone = form.cleaned_data['phone']
        usr_profile.save() 

        # automatic authentication and redirect!!

        user_created.backend = 'django.contrib.auth.backends.ModelBackend'
        auth.login(self.request, user_created)
        self.activation_code.delete()
        send_otp(phone_number=usr_profile.phone)
        return HttpResponseRedirect('/supplier/')

class RegistrationFormView(FormView):
    """
    Registration Form View...
    """
    form_class = RegistrationForm
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = 'subscriber/register.html'

    # @method_decorator(csrf_protect)
    # @method_decorator(never_cache)
    # def dispatch(self, *args, **kwargs):
    #     return super(RegistrationFormView, self).dispatch(*args, **kwargs)
    
    # def post(self, request, *args, **kwargs):
    #     """
    #     Handles POST requests, instantiating a form instance with the passed
    #     POST variables and then checked for validity.
    #     """
    #     form = self.get_form()
    #     if form.is_valid():
    #         return self.form_valid(form)
    #     else:
    #         return self.form_invalid(form)

    def form_valid(self, form):
        # create new user
        email_sent = form.save()

        context = self.get_context_data()
        context['first_name'] = form.cleaned_data['first_name']
        context['email'] = form.cleaned_data['email']
        context['email_sent'] = email_sent

        return render(self.request, 'subscriber/notifications/confirmation-sent.html', context)


class SupplierLoginFormView(FormView):
    """
    Supplier Login View
    """
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = 'subscriber/login.html'
    success_url = '/supplier/'

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        return super(SupplierLoginFormView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        """
        The user has provided valid credentials (this was checked in AuthenticationForm.is_valid()). So now we
        can check the test cookie stuff and log him in.
        :param form:
        :return:
        """
        self.check_and_delete_test_cookie()
        login(self.request, form.get_user())
        send_otp(phone_number=self.request.user.userprofile.phone)
        return super(SupplierLoginFormView, self).form_valid(form)

    def form_invalid(self, form):
        """
        The user has provided invalid credentials (this was checked in AuthenticationForm.is_valid()). So now we
        set the test cookie again and re-render the form with errors.
        :param form:
        :return:
        """
        self.set_test_cookie()
        return super(SupplierLoginFormView, self).form_invalid(form)

    def get_success_url(self):
        if self.success_url:
            redirect_to = self.success_url
        else:
            redirect_to = self.request.REQUEST.get(self.redirect_field_name, '')

        netloc = urlparse.urlparse(redirect_to)[1]
        if not redirect_to:
            redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)
        # Security check -- don't allow redirection to a different host.
        elif netloc and netloc != self.request.get_host():
            redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)
        return redirect_to

    def set_test_cookie(self):
        self.request.session.set_test_cookie()

    def check_and_delete_test_cookie(self):
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
            return True
        return False

    def get(self, request, *args, **kwargs):
        """
        Same as django.views.generic.edit.ProcessFormView.get(), but adds test cookie stuff
        """
        self.set_test_cookie()
        return super(SupplierLoginFormView, self).get(request, *args, **kwargs)



class UserOppurtunityPreferenceView(View):

    def post(self, request, *args, **kwargs):
        user_pref = request.user.userprofile.user_preferences
        if not user_pref:
            user_pref = {} 
        opp_preferences = {}

        if request.POST.get('set_aside_all'):
            opp_preferences['oppurtunity_options'] = "all"
        elif request.POST.getlist('oprotunity_options'):
            opp_preferences['oppurtunity_options'] = request.POST.getlist('oprotunity_options')
        if request.POST.get('notification_type'):
            opp_preferences['notification_type'] = request.POST.get('notification_type')
            if request.POST['notification_type'].lower() == 'daily':
                opp_preferences['max_emails'] = request.POST.get('max_emails', '100')
        user_pref['opprtunity_preferences'] = opp_preferences 
        request.user.userprofile.user_preferences = user_pref 
        request.user.userprofile.save()
        messages.add_message(request, messages.INFO, 'Your preferences has been saved successfully.')
        return HttpResponseRedirect(reverse('supplier:user_settings'))


class VerifyOtpFormView(FormView):
    """
    Supplier Login View
    """
    form_class = VerifyOtpForm
    template_name = 'subscriber/verify_otp.html'
    success_url = '/supplier/'

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        return super(VerifyOtpFormView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        if 'view' not in kwargs:
            kwargs['view'] = self
        if not self.request.user.is_anonymous():
            if self.request.user.userprofile.phone:
                phone = self.request.user.userprofile.phone
                kwargs['partial_phone_no'] = "{}".format(phone[-4:])
        return kwargs

    def get_form_kwargs(self):
        kwargs = super(VerifyOtpFormView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        """
        If the form is valid, redirect to the supplied URL.
        """
        self.request.session['opt_verified'] = True
        return HttpResponseRedirect(self.get_success_url())

subscriber/templates/subscriber/base.html
{% extends 'portal/base/body.html' %}
{% load static %}
    {% block extra_layout_scripts %}
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="{% static 'portal/assets/global/plugins/jquery-validation/js/jquery.validate.min.js' %}" type="text/javascript"></script>
        
        <script src="{% static 'portal/assets/global/plugins/jquery-validation/js/additional-methods.min.js' %}" type="text/javascript"></script>
        
        <script src="{% static 'portal/assets/global/plugins/select2/js/select2.full.min.js' %}" type="text/javascript"></script>
        
        <script src="{% static 'portal/assets/global/scripts/app.min.js' %}" type="text/javascript"></script>
        
        <script src="{% static 'subscriber/assets/pages/scripts/login.min.js' %}" type="text/javascript"></script>

    {% endblock extra_layout_scripts %}

subscriber/templates/subscriber/continue_registration.html
{% extends 'subscriber/login.html' %}

{% block title %}eSupplier | Registration{% endblock title %}


{% block body %}
    <div class="menu-toggler sidebar-toggler"></div>
    <!-- END SIDEBAR TOGGLER BUTTON -->
    <!-- BEGIN LOGO -->
    <div class="logo">
        <a href="{% url 'home' %}">
            <img src="{{ STATIC_URL }}subscriber/assets/images/logo.png" alt="" /> </a>
    </div>
    <!-- END LOGO -->
    <!-- BEGIN LOGIN -->
    <div class="content">

        <!-- BEGIN REGISTRATION FORM -->
        <form class="register-form" action="{% url 'subscriber:registration_landing_activate' activation_code %}" method="post" enctype="multipart/form-data">
            <h3 class="form-title font-blue">Complete your registration.</h3>

            {% csrf_token %}

            {% if form.form.non_field_errors %}

                <div class="alert alert-danger">
                <button class="close" data-close="alert"></button>

                {% for err in form.non_field_errors %}
                    <span> {{ err }}</span>
                {% endfor %}


            </div>
            {% endif %}

            <div class="form-group {% if form.first_name.errors %}has-error{% endif %}">
                <label class="control-label visible-ie8 visible-ie9">Name</label>

                {{ form.first_name }}

                {% if form.fist_name.errors %}
                    <span class="help-block" id="id_first_name-error">{{ form.first_name.errors }}.</span>
                {% endif %}

            </div>


            <div class="form-group {% if form.username.errors %}has-error{% endif %}">
                <label class="control-label visible-ie8 visible-ie9">Username</label>

                {{ form.username }}

                {% if form.username.errors %}
                    <span class="help-block" id="id_username-error">{{ form.username.errors }}.</span>
                {% endif %}

            </div>

            <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                <label class="control-label visible-ie8 visible-ie9">Email</label>
                {{ form.email }}

                {% if form.email.errors %}
                    <span class="help-block has-error" id="id_username-error">{{ form.email.errors }}.</span>
                {% endif %}

            </div>

            <div class="form-group {% if form.password1.errors %}has-error{% endif %}">

                <label class="control-label visible-ie8 visible-ie9">Password</label>
                {{ form.password1 }}

                {% if form.password1.errors %}
                    <span class="help-block has-error" id="id_password1-error">{{ form.password1.errors }}.</span>
                {% endif %}

            </div>

            <div class="form-group {% if form.password2.errors %}has-error{% endif %}">
                <label class="control-label visible-ie8 visible-ie9">Password</label>
                {{ form.password2 }}
                 {% if form.password2.errors %}
                    <span class="help-block has-error" id="id_password2-error">{{ form.password2.errors }}.</span>
                {% endif %}
            </div>
            
            
            <div class="form-group {% if form.password2.errors %}has-error{% endif %}">
                <label class="control-label visible-ie8 visible-ie9">Phone</label>
                {{ form.phone }}
                 {% if form.phone.errors %}
                    <span class="help-block has-error" id="id_password2-error">{{ form.phone.errors }}.</span>
                {% endif %}
            </div>

			<div class="form-group {% if form.password2.errors %}has-error{% endif %}">
                <label class="control-label">Select a profile Image</label>
                {{ form.profile_image }}
                 {% if form.profile_image.errors %}
                    <span class="help-block has-error" id="id_profile_image-error">{{ form.profile_image.errors }}.</span>
                {% endif %}
            </div>
			
            <div class="form-actions">
                <button type="submit" id="register-submit-btn" class="btn blue uppercase pull-right">Register</button>
            </div>

        </form>
        <!-- END REGISTRATION FORM -->

    </div>
    <div class="copyright">Copyright &copy; 2013 - 2015. eSupplierPortal. </div>
{% endblock body %}

subscriber/templates/subscriber/login.html
{% extends 'subscriber/base.html' %}
{% load static %}

{% block title %}eSupplier | User Login{% endblock title %}
{% block body_classes %}login{% endblock body_classes %}

{% block extra_css %}
    <link href="{% static 'subscriber/assets/pages/login.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'subscriber/assets/css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'subscriber/assets/css/responsive.css' %}" rel="stylesheet" type="text/css" />
{% endblock extra_css %}


{% block body %}
    <div class="menu-toggler sidebar-toggler"></div>
    <!-- END SIDEBAR TOGGLER BUTTON -->
    <!-- BEGIN LOGO -->
    <div class="logo">
        <a href="{% url 'portal:home' %}">
            <img src="{% static 'subscriber/assets/images/logo.png' %}" alt="" /> </a>
    </div>
    <!-- END LOGO -->
    <!-- BEGIN LOGIN -->
    <div class="content">

        <!-- BEGIN LOGIN FORM -->
        <form class="login-form" action="{% url 'subscriber:login' %}" method="post">
            {% csrf_token %}

            <h3 class="form-title font-blue">Hi there</h3>

            <div class="alert alert-danger display-hide">
                <button class="close" data-close="alert"></button>
                <span> Enter your username and password. </span>
            </div>

            {% if form.errors %}
             <div class="alert alert-danger">
                <button class="close" data-close="alert"></button>

               {% for err in form.non_field_errors %}
                <span> {{ err }}</span>
               {% endfor %}

                {% if form.username.errors %}
                    <span> {{ form.username.errors }}</span>
                {% endif %}

            </div>

            {% endif %}

            <div class="form-group ">
                <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                <label class="control-label visible-ie8 visible-ie9">Username</label>

                {{ form.username }}

            </div>

            <div class="form-group">
                <label class="control-label visible-ie8 visible-ie9">Password</label>
                {{ form.password }}
            </div>


            <div class="form-actions">
                <button type="submit" class="btn blue uppercase">Login</button>
                <label class="rememberme check">
                    <input type="checkbox" name="remember" value="1" />Remember </label>
                <a href="{% url 'subscriber:forget_password' %}" class="forget-password">Forgot Password?</a>
            </div>

            <div class="create-account">
                <p>
                    <a href="{% url 'subscriber:registration' %}" id="register-btn" class="uppercase">Create an account</a>
                </p>
            </div>
        </form>
        <!-- END LOGIN FORM -->


        <!-- BEGIN FORGOT PASSWORD FORM -->
        {% comment %}  <form class="forget-form" action="#" method="post">
            <h3 class="font-blue">Forget Password ?</h3>
            <p> Enter your e-mail address below to reset your password. </p>
            <div class="form-group">
                <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email" /> </div>
            <div class="form-actions">
                <button type="button" id="back-btn" class="btn btn-default">Back</button>
                <button type="submit" class="btn blue uppercase pull-right">Submit</button>
            </div>
        </form>{% endcomment %}
        <!-- END FORGOT PASSWORD FORM -->

    </div>
    <div class="copyright">Copyright &copy; 2013 - 2015. eSupplierPortal. </div>
{% endblock body %}

subscriber/templates/subscriber/register.html
{% extends 'subscriber/login.html' %}
{% load static %}
{% block title %}eSupplier | Registration{% endblock title %}

{% block body %}
     <style>
        .error{
            color: #CC0000;
            padding-top: 10px;
        }

        .error label{
            text-align: center;
        }
    </style>
    <div class="menu-toggler sidebar-toggler"></div>
    <!-- END SIDEBAR TOGGLER BUTTON -->
    <!-- BEGIN LOGO -->
    <div class="logo">
        <a href="{% url 'portal:home' %}">
            <img src="{% static 'subscriber/assets/images/logo.png' %}" alt="" /> </a>
    </div>
    <!-- END LOGO -->
    <!-- BEGIN LOGIN -->
    <div class="content">

        <!-- BEGIN REGISTRATION FORM -->
        <form class="register-form" action="{% url 'subscriber:registration' %}" method="post">
            <h3 class="form-title font-blue">Get started now!</h3>

            {% csrf_token %}

            {% if form.form.non_field_errors %}

                <div class="alert alert-danger">
                <button class="close" data-close="alert"></button>

                {% for err in form.non_field_errors %}
                    <span> {{ err }}</span>
                {% endfor %}


            </div>
            {% endif %}

            <div class="form-group {% if form.first_name.errors %}has-error{% endif %}">
                <label class="control-label visible-ie8 visible-ie9">Name</label>

                {{ form.first_name }}

                {% if form.fist_name.errors %}
                    <span class="help-block" id="id_first_name-error">{{ form.first_name.errors }}.</span>
                {% endif %}

            </div>


            <div class="form-group {% if form.username.errors %}has-error{% endif %}">
                <label class="control-label visible-ie8 visible-ie9">Username</label>

                {{ form.username }}

                {% if form.username.errors %}
                    <span class="help-block" id="id_username-error">{{ form.username.errors }}.</span>
                {% endif %}

            </div>

            <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                <label class="control-label visible-ie8 visible-ie9">Email</label>
                {{ form.email }}

                {% if form.email.errors %}
                    <span class="help-block has-error" id="id_username-error">{{ form.email.errors }}.</span>
                {% endif %}

            </div>

            <div class="form-group {% if form.password1.errors %}has-error{% endif %}">

                <label class="control-label visible-ie8 visible-ie9">Password</label>
                {{ form.password1 }}

                {% if form.password1.errors %}
                    <span class="help-block has-error" id="id_password1-error">{{ form.password1.errors }}.</span>
                {% endif %}

            </div>

            <div class="form-group {% if form.password2.errors %}has-error{% endif %}">
                <label class="control-label visible-ie8 visible-ie9">Password</label>
                {{ form.password2 }}
                 {% if form.password2.errors %}
                    <span class="help-block has-error" id="id_password2-error">{{ form.password2.errors }}.</span>
                {% endif %}
            </div>

            <div class="form-group margin-top-20 margin-bottom-20">

                <label class="check">
                    <input type="checkbox" name="tnc" /> I agree to the
                    <a href="javascript:;"> terms and  conditions</a>
                    <label for="tnc" class="error"></label>
                </label>

                <div id="register_tnc_error"> </div>

            </div>

            <div class="form-actions">
                <a href="{% url 'subscriber:login' %}" type="button" id="register-back-btn" class="btn btn-default">Back</a>
                <button type="submit" id="register-submit-btn" class="btn blue uppercase pull-right">Register</button>
            </div>

        </form>
        <!-- END REGISTRATION FORM -->

    </div>
    <div class="copyright">Copyright &copy; 2013 - 2015. eSupplierPortal. </div>
{% endblock body %}

{% block extra_layout_scripts %}
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
    <script type="application/javascript">

        $(document).ready(function(){
            $(".register-form").validate({
                rules: {
                    tnc: {
                        required:true
                    },
                    first_name: {
                        required:true ,
                        focus:true
                    },
                    email: {
                        required: true,
                        email:true
                    },
                },
                messages: {
                    tnc:{
                        required:'Accept the Terms and Conditions'
                    },
                    first_name: {
                        required:'This field is required'
                    },
                    email: {
                        required: "This field is required",
                        email: "Enter a valid email address.\r\tex: hello@abc.com",
                    }
                }
            });
        })

    </script>


{% endblock %}

subscriber/templates/subscriber/verify_otp.html
{% extends 'subscriber/base.html' %}

{% block title %}eSupplier | User Login{% endblock title %}
{% block body_classes %}login{% endblock body_classes %}

{% block extra_css %}
    <link href="{{ STATIC_URL }}subscriber/assets/pages/login.min.css" rel="stylesheet" type="text/css" />
    <link href="{{ STATIC_URL }}subscriber/assets/css/style.css" rel="stylesheet" type="text/css" />
    <link href="{{ STATIC_URL }}subscriber/assets/css/responsive.css" rel="stylesheet" type="text/css" />
{% endblock extra_css %}


{% block body %}
    <div class="menu-toggler sidebar-toggler"></div>
    <!-- END SIDEBAR TOGGLER BUTTON -->
    <!-- BEGIN LOGO -->
    <div class="logo">
        <a href="{% url 'home' %}">
            <img src="{{ STATIC_URL }}subscriber/assets/images/logo.png" alt="" /> </a>
    </div>
    <!-- END LOGO -->
    <!-- BEGIN LOGIN -->
    <div class="content">

        <!-- BEGIN LOGIN FORM -->
        <form class="login-form" action="{% url 'subscriber:verify_otp' %}" method="post">
            {% csrf_token %}

            <h3 class="form-title font-blue">Hi {{request.user|title}}</h3>

            <div class="alert alert-danger display-hide">
                <button class="close" data-close="alert"></button>
                <span> Enter OTP </span>
            </div>
			<p>Let's make sure it's really you. We've just sent a text message with a fresh verification code to the phone number ending in {{partial_phone_no}}.</br>
				Click.<a href="{% url 'subscriber:resend_otp' %}"> here</a> to resend verification code.</p>
			
            {% if form.errors %}
             <div class="alert alert-danger">
                <button class="close" data-close="alert"></button>

                {% if form.otp.errors %}
                    <span> {{ form.otp.errors }}</span>
                {% endif %}

            </div>

            {% endif %}

            <div class="form-group ">
                <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                <label class="control-label visible-ie8 visible-ie9">Verify OTP</label>
                {{ form.otp }}
            </div>




            <div class="form-actions">
                <button type="submit" class="btn blue uppercase">Verify</button>
            </div>


        </form>
        <a href="{% url 'subscriber:logout' %}">Logout</a>
        <!-- END LOGIN FORM -->


        <!-- BEGIN FORGOT PASSWORD FORM -->
      {% comment %}  <form class="forget-form" action="#" method="post">
            <h3 class="font-blue">Forget Password ?</h3>
            <p> Enter your e-mail address below to reset your password. </p>
            <div class="form-group">
                <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email" /> </div>
            <div class="form-actions">
                <button type="button" id="back-btn" class="btn btn-default">Back</button>
                <button type="submit" class="btn blue uppercase pull-right">Submit</button>
            </div>
        </form>{% endcomment %}
        <!-- END FORGOT PASSWORD FORM -->


    </div>
    <div class="copyright">Copyright &copy; 2013 - 2015. eSupplierPortal. </div>
{% endblock body %}