core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
	# path('', TemplateView.as_view(template_name='home.html'), name='home'),
	path('', include('portal.urls')),
	path('subscriber/', include('subscriber.urls')),
    path('admin/', admin.site.urls),
]

supplier/models.py
from django.db import models

# Create your models here.

subscriber/forms.py
from django import forms 
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.text import capfirst

class RegistrationForm(forms.Form):
    """
    Registration Form
    """
    first_name = forms.CharField(required=True, max_length=255)
    email = forms.EmailField(required=True)

    def __init__(self, request=None, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget = forms.TextInput(
            attrs={
            'class': 'form-control placeholder-no-fix',
            'autocomplete': 'off',
            'placeholder': 'Name'
        })

        self.fields['email'].widget = forms.EmailInput(
            attrs={
                'class': 'form-control placeholder-no-fix',
                'placeholder': 'Email'
            }
        )

    def clean_email(self):
        """
        Validating email address
        """
        email = self.cleaned_data['email']

        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("The email address is already in use")
        return email

    def save(self, send_email=True):
        """
        Save user and generate activation code..
        """
        email_sent = False

        activation_code, created = RegisterNowActivationCode.objects.get_or_create(
            email=self.cleaned_data['email'],
            defaults={
                'first_name': self.cleaned_data['first_name'],
                'code':md5(str(uuid.uuid4())).hexdigest()
            }
        )
        
        if created:
            email_sent = activation_code.send_email()

        if not created and activation_code.is_expired:
            activation_code.expire_data = datetime.now()+timedelta(days=2)
            activation_code.save()
            email_sent = activation_code.send_email()
        
        

        return email_sent


class CreateUserAccount(UserCreationForm):
    """
    This use by the flow of registration landing page form and supported for
    RegisterNowActivationCode data
    """
    profile_image = forms.ImageField()
    phone = forms.CharField(label="Phone",)

    class Meta:
        model = User
        fields = ("first_name", "username", "email", "password1", "password2",
                  "profile_image", 'phone'
                  )

    def __init__(self, request=None, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CreateUserAccount, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget = forms.HiddenInput(
            attrs={
                   'class': 'form-control placeholder-no-fix',
                   'autocomplete': 'off',
                   'placeholder': 'Name'
                   })

        self.fields['username'].widget = forms.TextInput(
            attrs={
                'class': 'form-control placeholder-no-fix',
                'autocomplete': 'off',
                'placeholder': 'Username'
            }
        )
        self.fields['email'].widget = forms.HiddenInput(
            attrs={
                'class': 'form-control placeholder-no-fix',
                'placeholder': 'Email'
            }
        )
        self.fields['password1'].widget = forms.PasswordInput(
            attrs={
                'class': 'form-control placeholder-no-fix',
                'autocomplete': 'off',
                'placeholder': 'Password'
            }
        )
        self.fields['password2'].widget = forms.PasswordInput(
            attrs={
                'class': 'form-control placeholder-no-fix',
                'autocomplete': 'off',
                'placeholder': 'Repeat the password'
            }
        )
        self.fields['phone'].widget = forms.TextInput(
            attrs={
                'class': 'form-control placeholder-no-fix',
                'autocomplete': 'off',
                'placeholder': 'Enter phone with country code'
            }
        )

    def save(self, send_email=False):
        # creating user without email activation...
        return super(CreateUserAccount, self).save(send_email)


class AuthenticationForm(forms.Form):
    """
    Login form, Subscribers
    """
    username = forms.CharField(max_length=254)
    password = forms.CharField(widget=forms.PasswordInput)

    error_messages = {
        'invalid_username': 'User does not exists',
        'invalid_login': 'Please enter a correct username and password, Note that both fields may be case-sensitive.',
        'inactive': 'this account is inactive, you need confirm your email'
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super(AuthenticationForm, self).__init__(*args, **kwargs)

        UserModel = get_user_model()

        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)

        self.fields['username'].widget = forms.TextInput(
            attrs={
                'class': 'form-control form-control-solid placeholder-no-fix',
                'placeholder': 'Username',
                'autocomplete': 'off'
            }
        )

        self.fields['password'].widget = forms.PasswordInput(
            attrs={
                'class': 'form-control form-control-solid placeholder-no-fix',
                'autocomplete': 'off',
                'placeholder': 'Password'
            }
        )

        if self.fields['username'].label is None:
            self.fields['username'].label = capfirst(self.username_field.verbose_name)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        UserModel = get_user_model()

        # if user does not exists
        if not UserModel.objects.filter(username=username):
            raise forms.ValidationError(
                self.error_messages['invalid_username'],
                code='invalid_login',
            )

        if username and password:
            self.user_cache = authenticate(username=username,
                                           password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in.
        """
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache


class PasswordResetForm(forms.Form):
    """
    Reset password
    """
    email = forms.EmailField(max_length=200)

    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)

        self.fields['email'].widget = forms.EmailInput(
            attrs={
                'class': "form-control placeholder-no-fix",
                'autocomplete': "off",
                'placeholder': 'Type your email here'
            }
        )

    def clean_email(self):
        """
        Validating email address
        """
        email = self.cleaned_data['email']

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("Account does not exist with this email.")
        return email


class PasswordChangeForm(forms.Form):
    """
    Password reset form
    """
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)


class VerifyOtpForm(forms.Form):
    """
    Reset password
    """
    otp = forms.CharField(max_length=200)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(VerifyOtpForm, self).__init__(*args, **kwargs)
        self.fields['otp'].widget = forms.TextInput(
            attrs={
                'class': 'form-control form-control-solid placeholder-no-fix',
                'placeholder': 'Enter otp',
                'autocomplete': 'off'
            }
        )

    def clean_otp(self):
        """
        Validating email address
        """
        otp = self.cleaned_data['otp']

        phone_num = self.request.user.userprofile.phone
        results = verify_otp(self.request, phone_num, otp)
        results = results['results']
        if not results['status']:
            raise forms.ValidationError(results['msg'])
        return otp

supplier/views.py
from django.shortcuts import render

# Create your views here.

core/templates/supplier/form/company_certification_form.html
<div class="row" ng-controller="CompCertificationController">
<div class="col-md-10">
	<form novalidate name="comp_certification" action="{% url 'company-certification' %}" method="post">{% csrf_token %}
	<input type="hidden" name="user" id="id_user" value="{{user.id}}">
	<input type="hidden" name="supplier" id="id_supplier" value="{{ supplier.id }}">
    <input type="hidden" name="company" id="id_company" value="{{ company.id }}">
		<table class="table">
		<tbody>
			<tr>
				<th width="200"><label for="id_certificate_name">Certificate name</label></th>
				<td>
					<input type="text" id="id_certificate_name" name="cert_name" ng-model="comp_certification.certificate_name" class="form-control" value="{[{comp_certification.certificate_name}]}" required autocomplete="off">

					<div ng-show="comp_certification.$dirty && comp_certification.certificate_name.$error.required && comp_certification.certificate_name.$touched">
						<p  class="bg-warning">Please enter Certificate name.</p>
					</div>
				</td>
			</tr>
			<tr>
				<th><label for="id_description">Description</label></th>
				<td>
					<textarea  id="id_description" name="description" ng-model="comp_certification.description" class="form-control" placeholder="Please put 'N/A' if no value available" required autocomplete="off">
                        {[{comp_certification.description}]}
                    </textarea>

					<div ng-show="comp_certification.$dirty && comp_certification.description.$error.required && comp_certification.description.$touched">
						<p  class="bg-warning">Please enter your Description.</p>
					</div>

				</td>
			</tr>
			<tr>
				<th><label for="id_cert_number">Cert number</label></th>
				<td>
					<input type="text" id="id_cert_number" name="cert_number" ng-model="comp_certification.cert_number" class="form-control"  placeholder="Please put 'N/A' if no value available" value="{[{comp_certification.cert_number}]}" required autocomplete="off">

					<div ng-show="comp_certification.$dirty && comp_certification.cert_number.$error.required && comp_certification.cert_number.$touched">
						<p  class="bg-warning">Please enter your Cert number.</p>
					</div>
				</td>
			</tr>
            <tr>
				<th><label for="id_category">Category</label></th>
				<td>
					<input type="text" id="id_category" name="category" ng-model="comp_certification.category" class="form-control"  placeholder="Please put 'N/A' if no value available" value="{[{comp_certification.category}]}" required autocomplete="off">

					<div ng-show="comp_certification.$dirty && comp_certification.category.$error.required && comp_certification.category.$touched">
						<p  class="bg-warning">Please enter your Category.</p>
					</div>
				</td>
			</tr>
            <tr>
				<th><label for="id_certification_date">Certification date</label></th>
				<td>
					<input type="date" id="id_certification_date" name="certification_date" ng-model="comp_certification.certification_date" class="form-control"  placeholder="Please put 'N/A' if no value available" value="{[{comp_certification.certification_date}]}" required autocomplete="off">

					<div ng-show="comp_certification.$dirty && comp_certification.certification_date.$error.required && comp_certification.certification_date.$touched">
						<p  class="bg-warning">Please enter your Certification date.</p>
					</div>
				</td>
			</tr>
            <tr>
				<th><label for="id_expire_date">Expire date</label></th>
				<td>
					<input type="date" id="id_expire_date" name="expire_date" ng-model="comp_certification.expire_date" class="form-control"  placeholder="Please put 'N/A' if no value available" value="{[{comp_certification.expire_date}]}" required autocomplete="off">

					<div ng-show="comp_certification.$dirty && comp_certification.expire_date.$error.required && comp_certification.expire_date.$touched">
						<p  class="bg-warning">Please enter your Expire date.</p>
					</div>
				</td>
			</tr>
            <tr>
				<th><label for="id_certificate_duration">Certificate duration</label></th>
				<td>
					<input type="text" id="id_certificate_duration" name="certificate_duration" ng-model="comp_certification.certificate_duration" class="form-control"  placeholder="Please put 'N/A' if no value available" value="{[{comp_certification.certificate_duration}]}" required autocomplete="off">

					<div ng-show="comp_certification.$dirty && comp_certification.certificate_duration.$error.required && comp_certification.certificate_duration.$touched">
						<p  class="bg-warning">Please enter your Certificate duration.</p>
					</div>
				</td>
			</tr>
            <tr>
				<th><label for="id_upload_certificate">Upload certificate</label></th>
				<td>
					<input type="file" id="id_upload_certificate" name="upload_certificate" ng-model="comp_license.upload_certificate" class="form-control" placeholder="Please put 'N/A' if no value available" value="{[{comp_license.upload_certificate}]}" required autocomplete="off"> 

					<div ng-show="comp_license.$dirty && comp_license.upload_certificate.$error.required && comp_license.upload_certificate.$touched">
						<p  class="bg-warning">Please upload your Upload certificate.</p>
					</div>

				</td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<th colspan="2">
					<button class="btn btn-primary">Save & Continue</button>
				</th>
			</tr>
		</tfoot>

		</table>
	</form>
</div>
</div>

core/templates/supplier/form/company_contact_form.html
<div class="row" ng-controller="CompContactController">
<div class="col-md-10">
	<form noviolate name="comp_contact_form" action="/supplier/profile/company/contacts/" method="post">{% csrf_token %}
	<input type="hidden" name="user" id="id_user" value="{{user.id}}">
	<input type="hidden" name="supplier" id="id_supplier" value="{{supplier.id}}">
	<input type="hidden" name="company" id="id_company" value="{{company.id}}">
	<table class="table">
		<tr>
			<td>
				<p class="bg-info" style="padding:5px;">Company Contacts</p>
			</td>
		</tr>
	</table>
		<table class="table">
		<tbody id="company_contact">
			<tr>
				<th width="250">
					<label for="id_name">* Contact Name</label>
				</th>
				<td>
					<input type="text" class="form-control" name="contact_name" id="id_contact_name" ng-minlength="3" ng-maxlength="20" ng-pattern="/^[ a-zA-Z0-9]+$/" ng-model="comp_contact.contact_name" value="{[{comp_contact.contact_name}]}" required autocomplete="off">

					<div class="error-msgs" ng-messages="comp_contact_form.contact_name.$error" ng-show="comp_contact_form.$dirty && comp_contact_form.contact_name.$touched">
                        <span ng-message="required" class="label label-warning">Please enter contact name</span>
                        <span ng-message="minlength" class="label label-danger">Should be at least 3 characters</span>
                        <span ng-message="maxlength" class="label label-danger">Should be less than 20 characters</span>
                        <span ng-message="pattern" class="label label-danger">Only alpha characters are accepted</span>
                    </div>

				</td>
				
			</tr>
			<tr>
				<th width="250">
					<label for="id_title">* Contact Title</label>
				</th>
				<td>
					<input type="text" class="form-control" name="contact_title" ng-minlength="3" ng-maxlength="20" ng-pattern="/^[ a-zA-Z0-9]+$/" id="id_contact_title" ng-model="comp_contact.contact_title" value="{[{comp_contact.contact_title}]}" required autocomplete="off">

                    <div class="error-msgs" ng-messages="comp_contact_form.contact_title.$error" ng-show="comp_contact_form.$dirty && comp_contact_form.contact_title.$touched">
                        <span ng-message="required" class="label label-warning">Please enter contact title</span>
                        <span ng-message="minlength" class="label label-danger">Should be at least 3 characters</span>
                        <span ng-message="maxlength" class="label label-danger">Should be less than 20 characters</span>
                        <span ng-message="pattern" class="label label-danger">Only alpha characters are accepted</span>
                    </div>
				</td>
				
			</tr>

			<tr>
				<th width="250">
					<label for="id_phone">* Contact Phone</label>
				</th>
				<td>
					<table class="table innertable">
						<tr>
							<td width="70%">
								<input type="text" class="form-control" name="contact_phone"  ng-pattern="/^(?:1-?)?(\d{3})[-\.]?(\d{3})[-\.]?(\d{4})$/" id="id_contact_phone" ng-model="comp_contact.contact_phone" value="{[{comp_contact.contact_phone}]}" required autocomplete="off">


                                <div class="error-msgs" ng-messages="comp_contact_form.contact_phone.$error" ng-show="comp_contact_form.$dirty && comp_contact_form.contact_phone.$touched">
                        <span ng-message="required" class="label label-warning">Please enter contact phone.</span>
                        <span ng-message="pattern" class="label label-danger">Phone numbers must be in XXX-XXX-XXXX format.</span>
                    </div>
							</td>
							<td>
								Ext.
							</td>
							<td>
								<input type="number" class="form-control" name="contact_phone_ext" ng-maxlength="5" id="id_phone_ext" ng-model="comp_contact.contact_phone_ext" value="{[{comp_contact.contact_phone_ext}]}" autocomplete="off">

                                <div class="error-msgs" ng-messages="comp_contact_form.contact_phone_ext.$error" ng-show="comp_contact_form.$dirty && comp_contact_form.contact_phone_ext.$touched">
                        <span ng-message="maxlength" class="label label-danger">Should be less than 5 characters</span>
                        <span ng-message="number" class="label label-danger">Only numbers.</span>
                    </div>
							</td>
						</tr>
					</table>
					
				</td>
				
			</tr>

			<tr>
				<th width="250">
					<label for="id_fax">Fax</label>
				</th>
				<td>
					<input type="text" class="form-control" name="contact_fax" id="id_contact_fax" ng-model="comp_contact.contact_fax" ng-pattern="/^(?:1-?)?(\d{3})[-\.]?(\d{3})[-\.]?(\d{4})$/" value="{[{comp_contact.contact_fax}]}" autocomplete="off">

                    <div class="error-msgs" ng-messages="comp_contact_form.contact_fax.$error" ng-show="comp_contact_form.$dirty && comp_contact_form.contact_fax.$touched">
                        <span ng-message="required" class="label label-warning">Please enter fax number.</span>
                        <span ng-message="pattern" class="label label-danger">Phone numbers must be in XXX-XXX-XXXX format.</span>
                    </div>

				</td>
				
			</tr>
			<tr>
				<th><label for="id_contact_email">* Email</label></th>
				<td>
					<input type="email" id="id_contact_email" name="contact_email" ng-model="comp_contact.contact_email" class="form-control" value="{[{comp_contact.contact_email}]}" required autocomplete="off"> 
						
						 <div class="form-group" class="has-error" ng-messages="comp_contact_form.contact_email.$error" ng-show="comp_contact_form.$dirty && comp_contact_form.contact_email.$touched">
                        <span ng-message="required" class="label label-warning">Please enter your company email id</span>
                        <span ng-message="email" class="label label-danger">This needs to be a valid email</span>
                    </div>

				</td>
			</tr>
			</tbody>
			</table>
			<table class="table">
				<tr>
					<td>
						<p class="bg-info" style="padding:5px;">Reference</p>
					</td>
				</tr>
			</table>
			<table class="table">
				<tr>
					<th width="250">
						<label for="id_ref_company_name">Company Name</label>
					</th>
					<td>
						<input type="text" class="form-control" name="ref_company_name" id="id_ref_company_name" ng-minlength="2" ng-maxlength="20" ng-pattern="/^[ a-zA-Z0-9]+$/" ng-model="comp_reference.ref_company_name" value="{[{comp_reference.ref_company_name}]}" autocomplete="off">


                        <div class="error-msgs" ng-messages="comp_contact_form.ref_company_name.$error" ng-show="comp_contact_form.$dirty && comp_contact_form.ref_company_name.$touched">
                        <span ng-message="required" class="label label-warning">Please enter company name</span>
                        <span ng-message="minlength" class="label label-danger">Should be at least 3 characters</span>
                        <span ng-message="maxlength" class="label label-danger">Should be less than 20 characters</span>
                        <span ng-message="pattern" class="label label-danger">Only alpha characters are accepted</span>
                    </div>
					</td>
					
				</tr>

				<tr>
					<th width="250">
						<label for="id_ref_contact_name">Contact Name</label>
					</th>
					<td>
						<input type="text" class="form-control" name="ref_contact_name" id="id_ref_contact_name" ng-minlength="2" ng-maxlength="20" ng-pattern="/^[ a-zA-Z0-9]+$/" ng-model="comp_reference.ref_contact_name" value="{[{comp_reference.ref_contact_name}]}" autocomplete="off">
						
					  <div class="error-msgs" ng-messages="comp_contact_form.ref_contact_name.$error" ng-show="comp_contact_form.$dirty && comp_contact_form.ref_contact_name.$touched">
                        <span ng-message="required" class="label label-warning">Please enter contact name</span>
                        <span ng-message="minlength" class="label label-danger">Should be at least 3 characters</span>
                        <span ng-message="maxlength" class="label label-danger">Should be less than 20 characters</span>
                        <span ng-message="pattern" class="label label-danger">Only alpha characters are accepted</span>
                    </div>
					</td>
					
				</tr>

				<tr>
					<th width="250">
						<label for="id_phone">Phone</label>
					</th>
					<td>
						<input type="text" class="form-control" name="ref_phone" id="id_ref_phone" ng-pattern="/^(?:1-?)?(\d{3})[-\.]?(\d{3})[-\.]?(\d{4})$/" ng-model="comp_reference.ref_phone" value="{[{comp_reference.ref_phone}]}" autocomplete="off">

                  <div class="error-msgs" ng-messages="comp_contact_form.ref_phone.$error" ng-show="comp_contact_form.$dirty && comp_contact_form.ref_phone.$touched">
                        <span ng-message="required" class="label label-warning">Please enter phone number.</span>
                        <span ng-message="pattern" class="label label-danger">Phone numbers must be in XXX-XXX-XXXX format.</span>
                    </div>


					</td>
					
				</tr>

				<tr>
					<th width="250">
						<label for="id_ref_email">Email</label>
					</th>
					<td>
						<input type="email" class="form-control" name="ref_email" id="id_ref_email" ng-model="comp_reference.ref_email" value="{[{comp_reference.ref_email}]}" autocomplete="off">

                        <div class="form-group" class="has-error" ng-messages="comp_contact_form.ref_email.$error" ng-show="comp_contact_form.$dirty && comp_contact_form.ref_email.$touched">
                        <span ng-message="required" class="label label-warning">Please enter an email id</span>
                        <span ng-message="email" class="label label-danger">This needs to be a valid email</span>
                    </div>




					</td>
					
				</tr>

				<tr>
					<th width="250">
						<label for="id_services_provided">Service Provided</label>
					</th>
					<td>
						<input type="text" class="form-control" name="ref_services_provided" id="id_ref_services_provided" ng-model="comp_reference.ref_services_provided" value="{[{comp_reference.ref_services_provided}]}" autocomplete="off"> 
						<div ng-show="comp_contact_form.$dirty && comp_contact_form.ref_services_provided.$error.required && comp_contact_form.ref_services_provided.$touched">
							<p  class="bg-warning">Please enter the service provided</p>
						</div>
					</td>
					
				</tr>
			</table>

		<table class="table">
			<tr>
				<th colspan="2">
					<button class="btn btn-primary" ng-disabled="comp_contact_form.$invalid">Save & Continue</button>
				</th>
			</tr>

		</table>
	</form>
</div>
</div>

core/templates/supplier/form/company_product_service_form.html
<div class="row" ng-controller="CompProServiceController">
<div class="col-md-12">
	<form novalidate name="comp_pro_service" action="/supplier/profile/company/products-services/" method="post">{% csrf_token %}
	<input type="hidden" name="user" id="id_user" value="{{user.id}}">
	<input type="hidden" name="supplier" id="id_supplier" value="{{ supplier.id }}">
    <input type="hidden" name="company" id="id_company" value="{{ company.id }}">
		<table class="table">
		<tbody>
			<tr>
				
				<td>
				<label for="id_naics_code">NAICS Code</label>
				<div style="text-align:right;">
					You can manually input the code in the space below or 
					<a ng-model="naics" ng-click='ShowSearchPage(naics)'>click here to search</a>
				</div>
				<textarea id="id_naics_code" name="naics_code" ng-model="comp_pro_service.naics_code" class="form-control" required autocomplete="off">
					
				</textarea>
				<span>Note: codes are separated by comma only</span>
					
				</td>
			</tr>
			<tr>
				<td>
				<label for="id_sic_code">SIC code</label>
				<div style="text-align:right;">
					You can manually input the code in the space below or 
					<a href="">click here to search</a>
				</div>
				<textarea id="id_sic_code" name="sic_code" ng-model="comp_pro_service.sic_code" class="form-control" required autocomplete="off">
					
				</textarea>
				<span>Note: codes are separated by comma only</span>
					
				</td>
			</tr>
			<tr>
				
				<td>
				<label for="id_unspsc_code">UNSPSC Code</label>
				<div style="text-align:right;">
					You can manually input the code in the space below or 
					<a href="">click here to search</a>
				</div>
				<textarea id="id_unspsc_code" name="unspsc_code" ng-model="comp_pro_service.unspsc_code" class="form-control"  placeholder="Please put 'N/A' if no value available" required autocomplete="off">
					
				</textarea>
				<span>Note: codes are separated by comma only</span>

				</td>
			</tr>
            <tr>
				
				<td>
				<label for="id_nigp_code">NIGP code</label>
				<div style="text-align:right;">
					You can manually input the code in the space below or 
					<a href="">click here to search</a>
				</div>
				<textarea id="id_nigp_code" name="nigp_code" ng-model="comp_pro_service.nigp_code" class="form-control"  placeholder="Please put 'N/A' if no value available" required autocomplete="off">
					
				</textarea>
				<span>Note: codes are separated by comma only</span>
					
					
				</td>
			</tr>
            <tr>				
				<td>
				<label for="id_cage_code">CAGE code</label>
				<div style="text-align:right;">
					You can manually input the code in the space below or 
					<a href="">click here to search</a>
				</div>
					<textarea id="id_cage_code" name="cage_code" ng-model="comp_pro_service.cage_code" class="form-control"  placeholder="Please put 'N/A' if no value available" required autocomplete="off">
						
					</textarea>
					<span><b>Note</b>: <i>codes are separated by comma only</i></span>
						
				</td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<th colspan="2">
					<button class="btn btn-primary">Save & Continue</button>
				</th>
			</tr>
		</tfoot>

		</table>
	</form>
</div>

<div id='search_modal' ng-show="show_search_modal" ng-blur="HideMe()">
	<input type="hidden" id="id_code_type" value="{{code_type}}">
	<table class="table">
		<tr>
			<th>#</th>
			<th>Select</th>
			<th>Common Keywords</th>
			<th>{{ code_type|upper }} code</th>
			<th>Title</th>
		</tr>
		<tr ng-repeat="code in codes">
			<td>{[{$index}]}</td>
			<td>
				<input type="checkbox" name="code" value="{[{ code.code }]}">
			</td>
			<td>
				{[{ code.common_keywords }]}
			</td>
			<td>
				{[{ code.code }]}
			</td>
			<td>
				{[{ code.title }]}
			</td>
		</tr>
	</table>
</div>

</div>

core/templates/supplier/form/question_info_form.html
<div class="row" ng-controller="UniqueController">
<div class="col-md-10">
{% if que_list %}
	<form novalidate name="comp_form" action="/supplier/profile/unique-question/" method="post">{% csrf_token %}
	<input type="hidden" name="user" id="id_user" value="{{user.id}}">
	<input type="hidden" name="supplier" id="id_supplier" value="{{supplier.id}}">
		<table class="table">
		<tbody>
		{% for que in que_list %}
			<tr>
				<th>
					<label for="id_{{ que.question.id }}">{{ que.question.question }}</label>
				</th>
				<td>
					<input type="text" class="form-control" name="{{ que.question.id }}" id="id_{{ que.question.id }}" value="{{ que.answer }}">
				</td>
			</tr>
		{% endfor %}
		</tbody>
		<tfoot>
			<tr>
				<th></th>
				<th align="right">
					<button class="btn btn-primary">Save & Continue</button>
				</th>
			</tr>
		</tfoot>

		</table>
	</form>
{% else %}
	<p class="alert alert-warning">No more question</p>
{% endif %}
</div>
</div>

core/templates/supplier/form/search.html
<div class="row" ng-controller="SearchPageController">
{% include "supplier/right-side-content.html" %}
</div>